name: Validate AWS SSM Config

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  validate-config:
    name: Validate SSM Config Before Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: af-south-1

    strategy:
      matrix:
        env: [dev, staging, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      # 游릵 ARCH: Dynamically map environment to correct OIDC role secret
      - name: Set OIDC role ARN for environment
        id: set-role
        run: |
          if [ "${{ matrix.env }}" = "dev" ]; then
            if [ -z "${{ secrets.AWS_OIDC_ROLE_ARN_DEV }}" ]; then
              echo "游린 CRITICAL: AWS_OIDC_ROLE_ARN_DEV secret is not set."
              exit 1
            fi
            echo "OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN_DEV }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" = "staging" ]; then
            if [ -z "${{ secrets.AWS_OIDC_ROLE_ARN_STAGING }}" ]; then
              echo "游린 CRITICAL: AWS_OIDC_ROLE_ARN_STAGING secret is not set."
              exit 1
            fi
            echo "OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN_STAGING }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" = "prod" ]; then
            if [ -z "${{ secrets.AWS_OIDC_ROLE_ARN_PROD }}" ]; then
              echo "游린 CRITICAL: AWS_OIDC_ROLE_ARN_PROD secret is not set."
              exit 1
            fi
            echo "OIDC_ROLE_ARN=${{ secrets.AWS_OIDC_ROLE_ARN_PROD }}" >> $GITHUB_ENV
          else
            echo "游린 CRITICAL: Unknown environment: ${{ matrix.env }}"
            exit 1
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 游릱 NOTE: Trivy and Python dependency scans are intentionally skipped for demo speed.
      # To re-enable, add the scan steps back here.

      - name: Validate SSM config for ${{ matrix.env }}
        run: make validate-config CDK_ENV=${{ matrix.env }}
